# Use the official Python image with a slimmed-down version of Debian
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

RUN pip install streamlit

# Copy the rest of the application code into the container
COPY . .

# Expose port 8501 for the Streamlit app
EXPOSE 8080

HEALTHCHECK CMD curl --fail http://localhost:8080/_stcore/health

# Command to run when starting the container
CMD ["streamlit", "run", "app.py", "--server.port=8080", "--server.address=0.0.0.0"]